# .github/workflows/test.yml
name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.7.0
      - name: Install
        run: bun install
      - name: Test and Coverage
        run: bun test:coverage

      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

      - name: Deploy docs
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        shell: bash
        run: |
          git checkout gh-pages
          git fetch
          rm -rf ./docs
          mkdir -p docs
          cd src
          bun i
          bun run build
          cd ..

          git config pull.rebase false
          git config --global user.email "ts438730@students.mimuw.edu.pl"
          git config --global user.name "Zuzanna Surowiec"
          git add -f docs/*
          git commit -m "build docs"
          git push -f
